version: "3.4"
services:
  builder:
    image: tree-sitter-builder
    build:
      dockerfile: Dockerfile
      pull: true
    volumes:
      - ./:/build
      - ./tree-sitter-module:/build/src
      - /usr/local:/usr/local
    tty: true
    stdin_open: true
    entrypoint: ./entrypoint.sh
